name: TestRunner

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkstyle check
      run: mvn -ntp checkstyle:check -Dcheckstyle.violationSeverity=warning

    - name: Compile the code
      run: mvn -ntp compile

    - name: Run tests for MainPresenter
      run: mvn -ntp test -Dtest=MainPresenterTest
